// Mocks generated by Mockito 5.4.4 from annotations
// in fitsolutions/test/widgets/sign_in_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i4;

import 'package:fitsolutions/modelo/user_data.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserData].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserData extends _i1.Mock implements _i2.UserData {
  @override
  String get nombreCompleto => (super.noSuchMethod(
        Invocation.getter(#nombreCompleto),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#nombreCompleto),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#nombreCompleto),
        ),
      ) as String);

  @override
  set nombreCompleto(String? _nombreCompleto) => super.noSuchMethod(
        Invocation.setter(
          #nombreCompleto,
          _nombreCompleto,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get tipo => (super.noSuchMethod(
        Invocation.getter(#tipo),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#tipo),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#tipo),
        ),
      ) as String);

  @override
  set tipo(String? _tipo) => super.noSuchMethod(
        Invocation.setter(
          #tipo,
          _tipo,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get docId => (super.noSuchMethod(
        Invocation.getter(#docId),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#docId),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#docId),
        ),
      ) as String);

  @override
  set docId(String? _docId) => super.noSuchMethod(
        Invocation.setter(
          #docId,
          _docId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get fechaNacimiento => (super.noSuchMethod(
        Invocation.getter(#fechaNacimiento),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#fechaNacimiento),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#fechaNacimiento),
        ),
      ) as String);

  @override
  set fechaNacimiento(String? _fechaNacimiento) => super.noSuchMethod(
        Invocation.setter(
          #fechaNacimiento,
          _fechaNacimiento,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get altura => (super.noSuchMethod(
        Invocation.getter(#altura),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  set altura(double? _altura) => super.noSuchMethod(
        Invocation.setter(
          #altura,
          _altura,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get peso => (super.noSuchMethod(
        Invocation.getter(#peso),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  set peso(double? _peso) => super.noSuchMethod(
        Invocation.setter(
          #peso,
          _peso,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get email => (super.noSuchMethod(
        Invocation.getter(#email),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#email),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#email),
        ),
      ) as String);

  @override
  set email(String? _email) => super.noSuchMethod(
        Invocation.setter(
          #email,
          _email,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void updateNombreCompleto(String? newNombreCompleto) => super.noSuchMethod(
        Invocation.method(
          #updateNombreCompleto,
          [newNombreCompleto],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateTipo(String? newTipo) => super.noSuchMethod(
        Invocation.method(
          #updateTipo,
          [newTipo],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateDocId(String? newDocId) => super.noSuchMethod(
        Invocation.method(
          #updateDocId,
          [newDocId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateFechaNacimiento(String? newFechaNacimiento) => super.noSuchMethod(
        Invocation.method(
          #updateFechaNacimiento,
          [newFechaNacimiento],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateAltura(double? newAltura) => super.noSuchMethod(
        Invocation.method(
          #updateAltura,
          [newAltura],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updatePeso(double? newPeso) => super.noSuchMethod(
        Invocation.method(
          #updatePeso,
          [newPeso],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateEmail(String? newEmail) => super.noSuchMethod(
        Invocation.method(
          #updateEmail,
          [newEmail],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dataFormBasic(Map<String, dynamic>? userData) => super.noSuchMethod(
        Invocation.method(
          #dataFormBasic,
          [userData],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void firstLogin(String? email) => super.noSuchMethod(
        Invocation.method(
          #firstLogin,
          [email],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateUserData(Map<String, dynamic>? userData) => super.noSuchMethod(
        Invocation.method(
          #updateUserData,
          [userData],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
